version: '3.8'

services:
  ml_pipeline:
    env_file: .env
    image: agent_researcher
    build:
      context: ..
      dockerfile: Dockerfile
      target: ml_pipeline
    deploy:
      replicas: 1
    restart: no
    command: python3 runner.py
